
[subsection Kettle]

To build Crimp the tool [syscmd kettle] is required.

[para] Crimp's build system requires it as an application found
in the PATH.

[para] Crimp requires version 1 or higher.

[para] The fossil repository providing releases of this tool (and its
associated package) can be found at
[uri http://core.tcl.tk/akupries/kettle].

[para] A mirror of the repository can be found at
[uri https://chiselapp.com/user/andreas_kupries/repository/Kettle].

[para] Use of either releases or of the head of the main branch is
recommended. Usage of branches is strongly discouraged as these are
used to work on experimental features and bugfixes of the tool. As
such their stability is not guaranteed.

[para] At the above url is also an explanation on how to build and
install Kettle, including a list of its dependencies.

[para] Its instructions will not be repeated here. If there are
problems with their directions please file a bug against the Kettle
project, and not Crimp.
